# Generated by Django 5.0.2 on 2024-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Profesión')),
            ],
        ),
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.RemoveField(
            model_name='autordb',
            name='profesion',
        ),
        migrations.AddField(
            model_name='autordb',
            name='profesion',
            field=models.ManyToManyField(to='ExpModule.profesion', verbose_name='Profesion'),
        ),
    ]
