# Generated by Django 5.0.2 on 2024-02-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpModule', '0002_profesion_alter_frasedb_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesion',
            new_name='ProfesionDb',
        ),
    ]
